[project]
name = "hw-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jaxlib==0.4.17",
    "numpy>=1.22.3",
    "rasa>=3.6.21",
    "transformers>=4.52.4",
]
